In [148]:
import numpy as np
import pandas as pd

In [149]:
train_set = pd.read_csv('train.csv')
train_set.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.

In [150]:
test_set = pd.read_csv('test.csv')
test_set.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary
0,2016-11-01 00:00:00.000 +0100,Mostly Cloudy,NaN,6.205556,4.527778,0.92,8.1466,297,0.0,0,1021.74,Partly cloudy starting in the afternoon.
1,2016-11-01 01:00:00.000 +0100,Mostly Cloudy,NaN,5.827778,4.177778,0.92,7.7763,296,0.0,0,1021.69,Partly cloudy starting in the afternoon.
2,2016-11-01 02:00:00.000 +0100,Partly Cloudy,NaN,5.311111,3.616667,0.93,7.6153,298,0.0,0,1021.61,Partly cloudy starting in the afternoon.
3,2016-11-01 03:00:00.000 +0100,Partly Cloudy,NaN,4.800000,3.088889,0.94,7.3738,300,0.0,0,1021.54,Partly cloudy starting in the afternoon.
4,2016-11-01 04:00:00.000 +0100,Clear,NaN,4.483333,2.883333,0.95,6.8103,303,0.0,0,1021.54,Partly cloudy starting in the afternoon.

In [151]:
train_set.shape

(94268, 12)

In [152]:
train_set['Cloud Cover'].value_counts()
test_set['Cloud Cover'].value_counts()

0    2185
Name: Cloud Cover, dtype: int64

In [153]:
train_set['Daily Summary'].value_counts()
test_set['Daily Summary'].value_counts()

Mostly cloudy throughout the day.                                    600
Partly cloudy throughout the day.                                    384
Partly cloudy starting in the morning.                               120
Partly cloudy until night.                                           120
Partly cloudy starting in the afternoon.                              96
Overcast throughout the day.                                          72
Clear throughout the day.                                             49
Foggy in the morning.                                                 48
Mostly cloudy starting in the morning.                                48
Foggy starting overnight continuing until morning.                    48
Foggy starting in the evening.                                        48
Foggy until morning.                                                  48
Partly cloudy until evening.                                          48
Partly cloudy starting overnight.                                     24
Rain throughout the day.                                              24
Mostly cloudy until evening.                                          24
Mostly cloudy until night.                                            24
Rain until afternoon.                                                 24
Mostly cloudy until morning.                                          24
Partly cloudy overnight.                                              24
Light rain starting overnight.                                        24
Drizzle until morning.                                                24
Partly cloudy starting in the morning continuing until afternoon.     24
Mostly cloudy starting in the afternoon.                              24
Drizzle starting in the evening.                                      24
Partly cloudy starting in the morning continuing until evening.       24
Partly cloudy starting in the morning continuing until night.         24
Partly cloudy starting in the afternoon continuing until evening.     24
Mostly cloudy starting overnight.                                     24
Light rain overnight.                                                 24
Foggy overnight.                                                      24
Rain until morning.                                                   24
Name: Daily Summary, dtype: int64

In [154]:
train_set.drop(['Cloud Cover'],axis=1,inplace=True)
test_set.drop(['Cloud Cover'],axis=1,inplace=True)

In [155]:
train_set.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,1016.51,Partly cloudy throughout the day.

In [156]:
train_set.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 143
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [157]:
train_set['Precip Type'].value_counts()
test_set['Precip Type'].value_counts()

rain    1811
Name: Precip Type, dtype: int64

In [158]:
train_set.dropna(inplace=True)
train_set.shape
test_set.dropna(inplace=True)

In [159]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le0= LabelEncoder()
le1 = LabelEncoder()
train_set['Precip Type']=le1.fit_transform(train_set['Precip Type'])
train_set['Summary']=le.fit_transform(train_set['Summary'])
train_set['Daily Summary']=le0.fit_transform(train_set['Daily Summary'])
train_set.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,19,0,9.472222,7.388889,0.89,14.1197,251,15.8263,1015.13,193
1,2006-04-01 01:00:00.000 +0200,19,0,9.355556,7.227778,0.86,14.2646,259,15.8263,1015.63,193
2,2006-04-01 02:00:00.000 +0200,17,0,9.377778,9.377778,0.89,3.9284,204,14.9569,1015.94,193
3,2006-04-01 03:00:00.000 +0200,19,0,8.288889,5.944444,0.83,14.1036,269,15.8263,1016.41,193
4,2006-04-01 04:00:00.000 +0200,17,0,8.755556,6.977778,0.83,11.0446,259,15.8263,1016.51,193

In [160]:
from sklearn.preprocessing import LabelEncoder
le2 = LabelEncoder()
le3 = LabelEncoder()
le4 = LabelEncoder()
test_set['Precip Type']=le2.fit_transform(test_set['Precip Type'])
test_set['Summary']=le3.fit_transform(test_set['Summary'])
test_set['Daily Summary']=le4.fit_transform(test_set['Daily Summary'])
test_set.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary
24,2016-11-10 00:00:00.000 +0100,8,0,4.455556,2.277778,0.91,8.9033,169,11.8496,1019.49,10
25,2016-11-10 01:00:00.000 +0100,8,0,4.100000,1.838889,0.93,8.9838,171,9.3863,1019.41,10
26,2016-11-10 02:00:00.000 +0100,8,0,3.761111,1.422222,0.93,9.0321,170,10.0464,1019.30,10
27,2016-11-10 03:00:00.000 +0100,8,0,3.483333,1.083333,0.93,9.0804,165,8.6618,1019.22,10
28,2016-11-10 04:00:00.000 +0100,8,0,3.333333,0.883333,0.92,9.1609,157,6.5205,1019.21,10

In [161]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_set[train_set.columns[1:-1]] = scaler.fit_transform(train_set[train_set.columns[1:-1]])
train_set.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,0.687603,-0.358359,-0.257516,-0.323361,0.795971,0.472293,0.588306,1.311252,0.103677,193
1,2006-04-01 01:00:00.000 +0200,0.687603,-0.358359,-0.269661,-0.338336,0.642932,0.493136,0.662646,1.311252,0.107901,193
2,2006-04-01 02:00:00.000 +0200,0.229423,-0.358359,-0.267348,-0.138489,0.795971,-0.993642,0.151560,1.102951,0.110520,193
3,2006-04-01 03:00:00.000 +0200,0.687603,-0.358359,-0.380699,-0.457625,0.489892,0.469977,0.755570,1.311252,0.114490,193
4,2006-04-01 04:00:00.000 +0200,0.229423,-0.358359,-0.332120,-0.361575,0.489892,0.029965,0.662646,1.311252,0.115335,193

In [162]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
test_set[test_set.columns[1:-1]] = scaler.fit_transform(test_set[test_set.columns[1:-1]])
test_set.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary
24,2016-11-10 00:00:00.000 +0100,0.920983,0.0,-0.965878,-0.996677,0.749166,-0.057392,-0.102025,0.246399,0.285991,10
25,2016-11-10 01:00:00.000 +0100,0.920983,0.0,-1.013418,-1.049268,0.864638,-0.040442,-0.080812,-0.347579,0.265191,10
26,2016-11-10 02:00:00.000 +0100,0.920983,0.0,-1.058729,-1.099196,0.864638,-0.030273,-0.091419,-0.188408,0.236591,10
27,2016-11-10 03:00:00.000 +0100,0.920983,0.0,-1.095870,-1.139805,0.864638,-0.020103,-0.144452,-0.522278,0.215791,10
28,2016-11-10 04:00:00.000 +0100,0.920983,0.0,-1.115926,-1.163770,0.806902,-0.003154,-0.229305,-1.038612,0.213191,10

In [163]:
date_column = test_set['Formatted Date']

In [164]:
import numpy as np
from datetime import datetime

def discretize_date(current_date, t):
    current_date = current_date[:-10]
    cdate = datetime.strptime(current_date, '%Y-%m-%d %H:%M:%S')

    if t == 'hour_sin':
        return np.sin(2 * np.pi * cdate.hour/24.0)
    if t == 'hour_cos':
        return np.cos(2 * np.pi * cdate.hour/24.0)
    if t == 'day_sin':
        return np.sin(2 * np.pi * cdate.timetuple().tm_yday/365.0)
    if t == 'day_cos':
        return np.cos(2 * np.pi * cdate.timetuple().tm_yday/365.0)

In [165]:
date_types = ['hour_sin', 'hour_cos', 'day_sin', 'day_cos']
for dt in date_types:
    train_set[dt] = train_set['Formatted Date'].apply(lambda x : discretize_date(x, dt))
train_set.drop(['Formatted Date'],axis=1,inplace=True)

In [166]:
date_types = ['hour_sin', 'hour_cos', 'day_sin', 'day_cos']
for dt in date_types:
    test_set[dt] = test_set['Formatted Date'].apply(lambda x : discretize_date(x, dt))
test_set.drop(['Formatted Date'],axis=1,inplace=True)

In [167]:
train_set.corr()

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary,hour_sin,hour_cos,day_sin,day_cos
Summary,1.000000,-0.116595,0.148246,0.144724,-0.113305,0.000399,0.023778,0.136393,0.145362,0.155380,-0.115330,-0.127050,0.046300,-0.101646
Precip Type,-0.116595,1.000000,-0.567658,-0.570190,0.236365,-0.069809,-0.043076,-0.319131,0.010172,-0.251461,0.081091,0.078052,0.109222,0.419416
Temperature (C),0.148246,-0.567658,1.000000,0.992616,-0.630585,0.009549,0.030480,0.392024,-0.005095,0.445040,-0.212764,-0.224199,-0.213088,-0.807760
Apparent Temperature (C),0.144724,-0.570190,0.992616,1.000000,-0.600865,-0.056404,0.029417,0.380663,0.000137,0.439919,-0.201036,-0.205653,-0.218644,-0.816364
Humidity,-0.113305,0.236365,-0.630585,-0.600865,1.000000,-0.225829,0.000547,-0.369251,0.004845,-0.374136,0.365708,0.394419,-0.043382,0.391281
Wind Speed (km/h),0.000399,-0.069809,0.009549,-0.056404,-0.225829,1.000000,0.104217,0.105184,-0.049036,-0.002270,-0.076573,-0.231619,0.130628,0.104385
Wind Bearing (degrees),0.023778,-0.043076,0.030480,0.029417,0.000547,0.104217,1.000000,0.050025,-0.011453,0.055573,-0.009678,0.006372,0.009570,-0.069053
Visibility (km),0.136393,-0.319131,0.392024,0.380663,-0.369251,0.105184,0.050025,1.000000,0.061307,0.461679,-0.056103,0.154133,0.040221,-0.433300
Pressure (millibars),0.145362,0.010172,-0.005095,0.000137,0.004845,-0.049036,-0.011453,0.061307,1.000000,0.054173,0.003372,0.013239,0.009874,-0.014850
Daily Summary,0.155380,-0.251461,0.445040,0.439919,-0.374136,-0.002270,0.055573,0.461679,0.054173,1.000000,-0.000164,-0.000110,-0.006373,-0.482386
hour_sin,-0.115330,0.081091,-0.212764,-0.201036,0.365708,-0.076573,-0.009678,-0.056103,0.003372,-0.000164,1.000000,0.000008,-0.000041,0.000045
hour_cos,-0.127050,0.078052,-0.224199,-0.205653,0.394419,-0.231619,0.006372,0.154133,0.013239,-0.000110,0.000008,1.000000,-0.000522,0.000246
day_sin,0.046300,0.109222,-0.213088,-0.218644,-0.043382,0.130628,0.009570,0.040221,0.009874,-0.006373,-0.000041,-0.000522,1.000000,0.009188
day_cos,-0.101646,0.419416,-0.807760,-0.816364,0.391281,0.104385,-0.069053,-0.433300,-0.014850,-0.482386,0.000045,0.000246,0.009188,1.000000

In [168]:
train_set.drop(['Apparent Temperature (C)'],axis=1,inplace=True)

In [169]:
test_set.drop(['Apparent Temperature (C)'],axis=1,inplace=True)

In [170]:
train_set.head()

,Summary,Precip Type,Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary,hour_sin,hour_cos,day_sin,day_cos
0,0.687603,-0.358359,-0.257516,0.795971,0.472293,0.588306,1.311252,0.103677,193,0.000000,1.000000,0.999991,0.004304
1,0.687603,-0.358359,-0.269661,0.642932,0.493136,0.662646,1.311252,0.107901,193,0.258819,0.965926,0.999991,0.004304
2,0.229423,-0.358359,-0.267348,0.795971,-0.993642,0.151560,1.102951,0.110520,193,0.500000,0.866025,0.999991,0.004304
3,0.687603,-0.358359,-0.380699,0.489892,0.469977,0.755570,1.311252,0.114490,193,0.707107,0.707107,0.999991,0.004304
4,0.229423,-0.358359,-0.332120,0.489892,0.029965,0.662646,1.311252,0.115335,193,0.866025,0.500000,0.999991,0.004304

In [171]:
y=train_set.iloc[:,8] 
X = train_set.loc[:, train_set.columns != 'Daily Summary']

In [172]:
y_test=test_set.iloc[:,8] 
X_test = test_set.loc[:, test_set.columns != 'Daily Summary']

In [173]:
X

,Summary,Precip Type,Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),hour_sin,hour_cos,day_sin,day_cos
0,0.687603,-0.358359,-0.257516,0.795971,0.472293,0.588306,1.311252,0.103677,0.000000,1.000000,0.999991,0.004304
1,0.687603,-0.358359,-0.269661,0.642932,0.493136,0.662646,1.311252,0.107901,0.258819,0.965926,0.999991,0.004304
2,0.229423,-0.358359,-0.267348,0.795971,-0.993642,0.151560,1.102951,0.110520,0.500000,0.866025,0.999991,0.004304
3,0.687603,-0.358359,-0.380699,0.489892,0.469977,0.755570,1.311252,0.114490,0.707107,0.707107,0.999991,0.004304
4,0.229423,-0.358359,-0.332120,0.489892,0.029965,0.662646,1.311252,0.115335,0.866025,0.500000,0.999991,0.004304
...,...,...,...,...,...,...,...,...,...,...,...,...
94263,0.687603,-0.358359,0.835513,-1.703672,-0.196988,-1.353819,1.376828,0.128851,-0.965926,0.258819,0.785650,-0.618671
94264,0.687603,-0.358359,0.611124,-1.397593,-0.998273,-1.567546,1.245676,0.131469,-0.866025,0.500000,0.785650,-0.618671
94265,0.687603,-0.358359,0.207455,-0.326318,-0.400783,-1.093630,1.376828,0.138143,-0.707107,0.707107,0.785650,-0.618671
94266,0.687603,-0.358359,0.081959,0.183814,-0.400783,-1.000706,1.376828,0.142282,-0.500000,0.866025,0.785650,-0.618671
94267,0.687603,-0.358359,0.113767,-0.224291,-1.097855,-1.047168,1.156955,0.140170,-0.258819,0.965926,0.785650,-0.618671

In [174]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(max_depth=32,n_estimators=120,random_state=1)
model.fit(X,y)
y_pred = model.predict(X_test)

In [175]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 3],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [176]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.0

In [177]:
y_pred

array([184, 184,  91, ..., 193, 193, 193])

In [180]:
transformed_daily = le0.inverse_transform(y_pred)

In [181]:
transformed_daily

array(['Partly cloudy starting overnight.',
       'Partly cloudy starting overnight.',
       'Mostly cloudy starting overnight.', ...,
       'Partly cloudy throughout the day.',
       'Partly cloudy throughout the day.',
       'Partly cloudy throughout the day.'], dtype=object)

In [185]:
date_column=date_column.values

In [207]:
transformed_daily.shape

(1811,)

In [208]:
date_column.shape

(1811,)

In [214]:
res = np.column_stack((date_column,transformed_daily))

In [215]:
res[1]

array(['2016-11-10 01:00:00.000 +0100',
       'Partly cloudy starting overnight.'], dtype=object)

In [216]:
pd.DataFrame(res).to_csv("res.csv")